spring:
  data:
    mongodb:
      uri: mongodb+srv://Rahul:Rahul123@fitness-microservice.vylrov5.mongodb.net/ai-service
      database: ai-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


rabbitmq:
 exchange:
  name: fitness.exchange
 queue:
  name: activity.queue
 routing:
  key: activity.tracking

gemini:
 api:
  url: ${GEMINI_API_URL}
  key: ${GEMINI_API_KEY}
